package com.prodaxis.bpmn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class QuestionAnswerParam implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	public static final java.lang.String LABEL_MAPPING_CLASS = "";

	@org.kie.api.definition.type.Label("Type d’usage du caisson hyperbare")
	private java.lang.String typeOfUse;
	@org.kie.api.definition.type.Label("Mode d’utilisation")
	private java.lang.String howToUse;
	@org.kie.api.definition.type.Label("Debit")
	private java.lang.Integer debit;
	@org.kie.api.definition.type.Label("Nombre d’usages prévus par an ")
	private java.lang.Integer numberOfUses;
	@org.kie.api.definition.type.Label("La quantité de caissons nécessaires ")
	private java.lang.Integer askedQuantity;
	@org.kie.api.definition.type.Label("Date demandée ")
	private java.util.Date customerRequestDate;

	@org.kie.api.definition.type.Label("Diamètre du caisson")
	private java.lang.Integer diameter;
	@org.kie.api.definition.type.Label("Numéro de contrat client")
	private java.lang.String salesContractId;
	@org.kie.api.definition.type.Label("Code client vente ")
	private java.lang.String soldToCustomerId;
	@org.kie.api.definition.type.Label("Code client livré ")
	private java.lang.String shipToCustomerId;
	@org.kie.api.definition.type.Label("Numéro d’affaire ")
	private java.lang.String projectId;

	@org.kie.api.definition.type.Label(value = "La quantité de tissu nécessaire ")
	private java.lang.Integer optionQuantity;

	public QuestionAnswerParam() {
	}

	public java.lang.String getTypeOfUse() {
		return this.typeOfUse;
	}

	public void setTypeOfUse(java.lang.String typeOfUse) {
		this.typeOfUse = typeOfUse;
	}

	public java.lang.String getHowToUse() {
		return this.howToUse;
	}

	public void setHowToUse(java.lang.String howToUse) {
		this.howToUse = howToUse;
	}

	public java.lang.Integer getDebit() {
		return this.debit;
	}

	public void setDebit(java.lang.Integer debit) {
		this.debit = debit;
	}

	public java.lang.Integer getNumberOfUses() {
		return this.numberOfUses;
	}

	public void setNumberOfUses(java.lang.Integer numberOfUses) {
		this.numberOfUses = numberOfUses;
	}

	public java.lang.Integer getAskedQuantity() {
		return this.askedQuantity;
	}

	public void setAskedQuantity(java.lang.Integer askedQuantity) {
		this.askedQuantity = askedQuantity;
	}

	public java.util.Date getCustomerRequestDate() {
		return this.customerRequestDate;
	}

	public void setCustomerRequestDate(java.util.Date customerRequestDate) {
		this.customerRequestDate = customerRequestDate;
	}

	public java.lang.Integer getDiameter() {
		return this.diameter;
	}

	public void setDiameter(java.lang.Integer diameter) {
		this.diameter = diameter;
	}

	public java.lang.String getSalesContractId() {
		return this.salesContractId;
	}

	public void setSalesContractId(java.lang.String salesContractId) {
		this.salesContractId = salesContractId;
	}

	public java.lang.String getSoldToCustomerId() {
		return this.soldToCustomerId;
	}

	public void setSoldToCustomerId(java.lang.String soldToCustomerId) {
		this.soldToCustomerId = soldToCustomerId;
	}

	public java.lang.String getShipToCustomerId() {
		return this.shipToCustomerId;
	}

	public void setShipToCustomerId(java.lang.String shipToCustomerId) {
		this.shipToCustomerId = shipToCustomerId;
	}

	public java.lang.String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(java.lang.String projectId) {
		this.projectId = projectId;
	}

	public java.lang.Integer getOptionQuantity() {
		return this.optionQuantity;
	}

	public void setOptionQuantity(java.lang.Integer optionQuantity) {
		this.optionQuantity = optionQuantity;
	}

	public QuestionAnswerParam(java.lang.String typeOfUse,
			java.lang.String howToUse, java.lang.Integer debit,
			java.lang.Integer numberOfUses, java.lang.Integer askedQuantity,
			java.util.Date customerRequestDate, java.lang.Integer diameter,
			java.lang.String salesContractId,
			java.lang.String soldToCustomerId,
			java.lang.String shipToCustomerId, java.lang.String projectId,
			java.lang.Integer optionQuantity) {
		this.typeOfUse = typeOfUse;
		this.howToUse = howToUse;
		this.debit = debit;
		this.numberOfUses = numberOfUses;
		this.askedQuantity = askedQuantity;
		this.customerRequestDate = customerRequestDate;
		this.diameter = diameter;
		this.salesContractId = salesContractId;
		this.soldToCustomerId = soldToCustomerId;
		this.shipToCustomerId = shipToCustomerId;
		this.projectId = projectId;
		this.optionQuantity = optionQuantity;
	}

}